frontend:
  image:
    repository: ariefshaik007/simplenotes-frontend
    tag: "17948627399"
  replicaCount: 1
  service:
    type: ClusterIP 
    port: 80

backend:
  image:
    repository: ariefshaik007/simplenotes-backend
    tag: "17948172393"
  replicaCount: 1
  service:
    port: 5001

database:
  password: bXlzZWNyZXRwYXNzd29yZA==

ingress:
  enabled: true
  host: simplenotes.com